@BASE_URL=http://localhost:3000/users


POST {{BASE_URL}}
Content-Type: application/json

{
  "firstName": "Gabriel",
  "lastName": "Tavares",
  "birthdate": "2005-04-19",
  "email": "gabrieafsdsddd@gmail.com",
  "password": "12345",
  "phoneNumber": "11989797961",
  "cpf": "12345632178",
  "address": {
    "postalCode": "12345678",
    "addressLine": "123 Main Street",
    "district": "Downtown",
    "city": "Metropolis",
    "state": "Metropolis State",
    "addressNumber": "123",
    "complement": "asda"
  },
  "measurements": {
    "shoeSize": "42",
    "shirtSize": "XL",
    "pantsSize": "L",
    "height": "170"
  }
}

###GET para algo
GET {{BASE_URL}}